name: Build Core Rulebook
run-name: Build core rulebook from ${{ github.ref }}
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y texlive-base texlive-xetex fonts-open-sans
      - run: sudo tlmgr init-usertree
      - run: |
          sudo tlmgr update \
            import \
            textcomp \
            titlesec \
            makecell \
            imakeidx \
            glossaries \
            hyperref \
            fontspec \
            tocbibind \
            blindtext \
            caption \
            multicol \
            tabularx \
            xltabular \
            geometry \
            xcolor \
            enumitem \
            siunitx \
            varwidth
      - run: make
      - name: Upload core rulebook as artifact
        uses: actions/upload-artifact@v4
        with:
          name: core-rulebook
          path: "./The Unclassed System Core Rulebook.pdf"
